// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTT-dS3p-dysMGb1L1ifPvxMOmT8ItPTA',
    appId: '1:535814593524:web:27fdf608a059fdb2d9b7a1',
    messagingSenderId: '535814593524',
    projectId: 'born-again-memories',
    authDomain: 'born-again-memories.firebaseapp.com',
    storageBucket: 'born-again-memories.firebasestorage.app',
    measurementId: 'G-XX29X381TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVEHwn2orUT_erl2kZCgPG1VikSpWorRU',
    appId: '1:535814593524:android:c49d8d992c758102d9b7a1',
    messagingSenderId: '535814593524',
    projectId: 'born-again-memories',
    storageBucket: 'born-again-memories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB72zAL5tsY3AbIaz9H6Q8f2adv31LTzvk',
    appId: '1:535814593524:ios:75a148255a397b63d9b7a1',
    messagingSenderId: '535814593524',
    projectId: 'born-again-memories',
    storageBucket: 'born-again-memories.firebasestorage.app',
    iosClientId: '535814593524-2ivnq4cakusq84cd3c65la319getapt1.apps.googleusercontent.com',
    iosBundleId: 'com.tibinthomas.bornAgainMemories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB72zAL5tsY3AbIaz9H6Q8f2adv31LTzvk',
    appId: '1:535814593524:ios:515057fd62fded58d9b7a1',
    messagingSenderId: '535814593524',
    projectId: 'born-again-memories',
    storageBucket: 'born-again-memories.firebasestorage.app',
    iosClientId: '535814593524-6dnrg7ake15fjh9lv6ioelfg03o9af6c.apps.googleusercontent.com',
    iosBundleId: 'com.tibinthomas.bornAgainMemories',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTT-dS3p-dysMGb1L1ifPvxMOmT8ItPTA',
    appId: '1:535814593524:web:0f249faf282e54f3d9b7a1',
    messagingSenderId: '535814593524',
    projectId: 'born-again-memories',
    authDomain: 'born-again-memories.firebaseapp.com',
    storageBucket: 'born-again-memories.firebasestorage.app',
    measurementId: 'G-WDG0XEGT5Q',
  );
}
